# Generated by Django 6.1.1 on 2026-09-28 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField()),
                ('codigo', models.CharField(max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_non_negative')],
            },
        ),
    ]
